services:
    rules.admin:
        class: Zitec\RuleEngineBundle\Admin\RuleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Rules", show_in_dashboard: false }
        arguments:
            - ~
            - Zitec\RuleEngineBundle\Entity\Rule
            - ~

    rules.doctrine_behaviors.rule:
        class: Zitec\RuleEngineBundle\DoctrineBehaviors\RuleSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    rule_engine.form.type:
        class: Zitec\RuleEngineBundle\Form\Type\RuleEngineType
        tags:
            - {name: form.type}

    rule_engine.autocomplete:
        class: Zitec\RuleEngineBundle\Autocomplete\AutocompleteManager

    rule_engine.evaluator:
        class: Zitec\RuleEngineBundle\Service\RuleEvaluator

    rule_engine.expression_array_functions:
        class: Zitec\RuleEngineBundle\Service\ArrayExpressionLanguageProvider
        tags:
            - { name: rule_engine.expression_function_provider }

    rule_engine.orchestrator:
        class: Zitec\RuleEngineBundle\Service\Orchestrator
        arguments: ['@doctrine.orm.entity_manager']

    rule_engine.condition.current_date:
        class: Zitec\RuleEngineBundle\Conditions\CurrentDate
        public: false

    rule_engine.condition.current_day:
        class: Zitec\RuleEngineBundle\Conditions\CurrentDay
        public: false

    rule_engine.condition.current_time:
        class: Zitec\RuleEngineBundle\Conditions\CurrentTime
        public: false
